# Generated by Django 5.1.6 on 2025-03-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_user",
            field=models.IntegerField(choices=[(1, "Admin"), (0, "Client")], default=0),
        ),
    ]
